### ISSUE TITLE
AWS Java - Unrecognized SSL message, plaintext connection?

### ISSUE THREAD

**Issue by adamgerst** [mhart/dynalite#101]
I'm setting up a local kinesis stream using localstack and when it comes to creating tables in dynamodb, it's crashing complaining about SSL

```22:12:33.120 [error] com.amazonaws.services.kinesis.leases.impl.LeaseManager [] - Failed to get table status for alert
com.amazonaws.services.kinesis.leases.exceptions.DependencyException: com.amazonaws.SdkClientException: Unable to execute HTTP request: Unrecognized SSL message, plaintext connection?
	at com.amazonaws.services.kinesis.leases.impl.LeaseManager.tableStatus(LeaseManager.java:163)
	at com.amazonaws.services.kinesis.leases.impl.LeaseManager.createLeaseTableIfNotExists(LeaseManager.java:108)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisClientLibLeaseCoordinator.initialize(KinesisClientLibLeaseCoordinator.java:307)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.initialize(Worker.java:495)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.run(Worker.java:436)
	at com.contxt.kinesis.ManagedKinesisWorker.run(KinesisSource.scala:131)
	at com.contxt.kinesis.KinesisSource$.$anonfun$createAndStartKclWorker$1(KinesisSource.scala:114)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

When I start up my java application, I make sure to disable SSL certs by passing in the ```-Dcom.amazonaws.sdk.disableCertChecking``` option and set the environment variable ```AWS_CBOR_DISABLE=true```

Any ideas on what's going on?  My app isn't having any issues connecting to kinesis at all.

**Comment by mhart** [comment]
Is the java kinesis client trying to connect to DynamoDB? I'm unfamiliar with that library – maybe there are some settings you need to set to for the connection to DynamoDB?

**Comment by adamgerst** [comment]
It is, the client is trying to create tables that a kinesis client needs to store information about the stream in.  I'm able to use the aws cli tool to do CRUD with dynalite.  The connection is being set correctly, I have it going to the correct port.  Is there any sort of debug options I can use when I start localstack/dynalite that can give me any information on the dynamo side of things?  The exception that the client is throwing internally says that it is usually thrown when there is an internal server error for dynamo.

**Comment by adamgerst** [comment]
Hmmm, this all seems to be related to the SSL madness that is AWS CLI, KPL, and KCL when using kinesalite and dynalite.  People have posted about this problem in several other issues so I'm going to close this issue.

**Comment by Ghilteras** [comment]
@adamgerst can you link the related issues instead of just closing the issue like this otherwise people coming from a google search (like me) don't know where to go from here or what other issues are linked to this one (since there is none) without having to manually do another search.
