### ISSUE TITLE
Tests failing due to breaking change in abstract-leveldown

### ISSUE THREAD

**Issue by willwhite** [mhart/dynalite#32]
A breaking change in the new release of abstract-leveldown (an upstream dependency of memdown) is causing tests to fail unexpectedly in this project. I have reported the problem in https://github.com/Level/abstract-leveldown/issues/61 but I am opening this issue to help anyone else who might encounter this in the mean time.

The test failures looks like this:

```
/Users/willwhite/dynalite/node_modules/memdown/node_modules/abstract-leveldown/abstract-leveldown.js:13
    throw new Error('constructor requires a non empty location string')
          ^
Error: constructor requires a non empty location string
    at MemDOWN.AbstractLevelDOWN (/Users/willwhite/dynalite/node_modules/memdown/node_modules/abstract-leveldown/abstract-leveldown.js:13:11)
    at new MemDOWN (/Users/willwhite/dynalite/node_modules/memdown/memdown.js:124:21)
    at MemDOWN (/Users/willwhite/dynalite/node_modules/memdown/memdown.js:122:12)
    at LevelUP.open (/Users/willwhite/dynalite/node_modules/levelup/lib/levelup.js:115:18)
    at new LevelUP (/Users/willwhite/dynalite/node_modules/levelup/lib/levelup.js:87:8)
    at LevelUP (/Users/willwhite/dynalite/node_modules/levelup/lib/levelup.js:47:12)
    at Object.create (/Users/willwhite/dynalite/db/index.js:30:12)
    at dynalite (/Users/willwhite/dynalite/index.js:23:26)
    at Object.<anonymous> (/Users/willwhite/dynalite/test/helpers.js:49:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/willwhite/dynalite/test/batchGetItem.js:1:77)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/willwhite/dynalite/node_modules/mocha/lib/mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/willwhite/dynalite/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (/Users/willwhite/dynalite/node_modules/mocha/lib/mocha.js:422:31)
    at Object.<anonymous> (/Users/willwhite/dynalite/node_modules/mocha/bin/_mocha:398:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by mhart** [comment]
@willwhite thanks for the report but this was actually fixed in 0.12.0! Try updating and see if that works for you.

**Comment by mhart** [comment]
Technically it was this commit that fixed it: https://github.com/mhart/dynalite/commit/3c56a499a7b7a73b1c6c828f53c497280e7819fa – it was only a couple of hours ago so you may not have had a chance to check it out yet.

**Comment by mhart** [comment]
That build passed as well: https://travis-ci.org/mhart/dynalite/builds/62318633 – so I'm going to close this. But please reopen if you can reliably reproduce.

**Comment by willwhite** [comment]
Yep that works! Thanks for fixing this so quickly. I'm upgrading everywhere now.
