### ISSUE TITLE
Cannot find module 'memdown'

### ISSUE THREAD

**Issue by mlimaloureiro** [mhart/dynalite#45]
Hi guys,

I've a provision script that installs dynalite and it stopped working.

```
> var dynalite = require('dynalite')
Error: Cannot find module 'memdown'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/vagrant/node_modules/dynalite/db/index.js:4:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Seems something happened with `memdown` dependency. I've tested globally, and locally and it always asks for memdown.

Any ideas what's happening ? 

Thanks

**Comment by mhart** [comment]
@mlimaloureiro It's definitely specified as a dependency: https://github.com/mhart/dynalite/blob/c7f8705d4701920d159eb1c2a35da17c5da7e746/package.json#L31

Does `memdown` exist for you in `node_modules` after you've done an `npm install`?

**Comment by mlimaloureiro** [comment]
yep, forgot to say that. it's in my node_modules folder. anyway just found out that if I update my npm version it works fine. so probly just that. just found it weird that it worked before

**Comment by mhart** [comment]
@mlimaloureiro which npm version were you using before and what did you upgrade to?

I'm gonna close this now that you appear to have solved it – but if you find that it happens again, and it's somehow related to this module (and not npm itself), feel free to reopen
