### ISSUE TITLE
Error: Cannot find module 'memdown'

### ISSUE THREAD

**Issue by sarxos** [mhart/dynalite#51]
Hello @mhart , 

I'm on Ubuntu 14.04 and following these steps:

```plain
curl -sL https://deb.nodesource.com/setup | sudo bash -
sudo apt-get -y install nodejs
sudo apt-get -y install build-essential
sudo npm install -g dynalite
sudo /usr/bin/dynalite --port 8080
```

And getting:

```plain
sarxos@sarxos-comp:~/workspace$ sudo /usr/bin/dynalite --port 8080

module.js:340
    throw err;
          ^
Error: Cannot find module 'memdown'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/dynalite/db/index.js:4:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

I've executed  ```sudo npm install -g memdown``` as well, but it didn't help.

The ```npm``` version:

```plain
sarxos@sarxos-comp:~/workspace$ sudo npm -v
3.7.5
```

And node version:

```plain
sarxos@sarxos-comp:~/workspace$ node --version
v0.10.42
```

It would be great if you have some ideas of how this could be resolved.

**Comment by mhart** [comment]
Did you install it first with an old version of npm? There are some bugs with npm v1.x – which, given your very old version of Node, may have been installed initially before you upgraded to npm v3.x

Try `npm cache clean` and then install again and see how you go.

**Comment by sarxos** [comment]
Hi @mhart,

Thank you for your support! I confirm that everything is working well after removing and installing again nodejs and all node modules.

For the users who experience the same issue - below is full procedure I followed:

I removed nodejs by:

```
sudo apt-get remove nodejs
```

And then removed global ```node_modules``` by:

```
sudo rm -rf /usr/local/lib/node_modules/
```

Then I re-installed nodejs:

```
sarxos@sarxos-comp:~/workspace$ sudo apt-get install nodejs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 0 to remove and 12 not upgraded.
Need to get 0 B/4376 kB of archives.
After this operation, 22,2 MB of additional disk space will be used.
Selecting previously unselected package nodejs.
(Reading database ... 539663 files and directories currently installed.)
Preparing to unpack .../nodejs_0.10.42-1nodesource1~trusty1_amd64.deb ...
Unpacking nodejs (0.10.42-1nodesource1~trusty1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up nodejs (0.10.42-1nodesource1~trusty1) ...
```

The ```npm```:

```
sarxos@sarxos-comp:~/workspace$ sudo npm install -g npm@lates
```

And dynalite:

```
sarxos@sarxos-comp:~/workspace$ sudo npm install -g dynalite
```

Start it:

```
sarxos@sarxos-comp:~/workspace$ sudo dynalite --port 8080
Listening at http://0.0.0.0:8080
```

Everything is working after this is done :)

**Comment by mhart** [comment]
I'd also consider using a newer version of Node.js to be honest – the v0.10 line is 3 years old now and will become increasingly rarer. v4.x is the LTS release and can be installed on Ubuntu like so:

```
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs
```

Instructions for various distros here: https://github.com/nodesource/distributions
