### ISSUE TITLE
ConfigError: Missing region in config

### ISSUE THREAD

**Issue by golden88** [mhart/dynalite#96]
Hello, when using dynalite together with the `aws-sdk`, I am getting a ConfigError from the `aws-sdk`.
Apparently 
```
const dynamo = new AWS.DynamoDB({
  endpoint: 'http://localhost:4567'
});
```
is not enough anymore to get started. When I set the region to `eu-west-1`, 
I am getting
```
Error: connect ENETUNREACH 169.254.169.254:80
[0]       at Object._errnoException (util.js:992:11)
[0]       at _exceptionWithHostPort (util.js:1014:20)
[0]       at TCPConnectWrap.afterConnect [as oncomplete] (n
```
please advise.

**Comment by mhart** [comment]
Try:

```js
const dynamo = new AWS.DynamoDB({ endpoint: new AWS.Endpoint('http://localhost:4567') })
```
and let me know if that works

**Comment by golden88** [comment]
hey @mhart,
getting the same error with your line.

**Comment by mhart** [comment]
I think you have some sort of DNS issue – 169.254.x.x is a Link-local address: https://en.wikipedia.org/wiki/Link-local_address

Are you running this in Docker or something?

**Comment by mhart** [comment]
Any update on this?

**Comment by mhart** [comment]
Closing due to lack of activity

**Comment by Gerst20051** [comment]
This is the solution:

```
const dynamodb = new AWS.DynamoDB({ endpoint: 'http://localhost:4567', region: 'localhost' });
```
